// Generated by https://quicktype.io
export interface Navigation {
    navigation?:            any;
}

export interface LoginData {
    email:                  string;
    password:               string;
}

export interface AgentData {
    name:                   string;
    first_name:             string;
    second_surname:         string;
    phone:                  string;
    agent_id:               any;
}

export interface ScheduleData {
    agent_id:               number;
}

export interface User {
    id:                     number;
    role_id:                number | null;
    name:                   string | null;
    paternal_surname:       string | null;
    maternal_surname:       string | null;
    picture:                string | null;
    email:                  string | null;
    created_at:             Date;
    updated_at:             Date;
}

export interface LoginResponse {
    expires_at:             Date;
    user:                   User;
    status:                 boolean;
    token:                  string | null;
    token_type:             string | null;
}

export interface RefreshTokenResponse {
    expires_at:             Date;
    status:                 boolean;
    type:                   string | null;
}

export interface DataAgentResponse {
    id:                     number;
    employee_number:        number;
    user_id:                number;
    notes:                  string | null;
    is_active:              number;
    created_by:             null;
    updated_by:             null;
    created_at:             Date;
    updated_at:             Date;
}

export interface ProspectsResponse {
    id:                     number;
    name:                   string;
    first_name:             string;
    second_surname:         string;
    phone:                  number;
    agent_id:               number;
    notes:                  null;
    is_active:              number;
    created_by:             null;
    updated_by:             null;
    created_at:             Date;
    updated_at:             Date;
}

export interface ScheduleResponse {
    id:                         number;
    appointment_date:       string;
    appointment_hour:       string;
    duration:               string;
    is_done:                number,
    agent_id:               number;
    prospect_id:            number;
    appointment_type_id:    number;
    notes:                  null;
    is_active:              number;
    created_by:             null;
    updated_by:             null;
    created_at:             Date;
    updated_at:             Date;
}

export interface ArticleResponse {
    id:                     number,
    name:                   string;
    url_image:              string;
    content:                string;
    notes:                  string;
    is_active:              number;
    created_by:             null;
    updated_by:             null;
    created_at:             Date;
    updated_at:             Date;
}

export interface BinnacleResponse {
    name:                   string;
    amount:                 number;
    points:                 number;
}

export interface PolicyTypeResponse {
    id:                   string;
    name:                 string;
    notes:                number;
    is_active:            number;
    created_by:           number;
    updated_by:           number;
    created_at:           number;
    updated_at:           number;
}

export interface GoalPercentageResponse {
    agent_id:             number;
    game_id:              number;
    policies_sold_amount: number;
    goal:                 number;
    goal_percentage:      number;
}